    # -*- coding: utf-8 -*-
    """
    Created on Mon Jan 29 15:31:24 2018
    
    @author: wyq
    """
    
    import numpy
    import pandas
    f=open("D:\\prediction of storm and rain\\data sets\\DUQUSHUJU.txt",'r')
    s=f.readlines()
    sa=[0 for x in range(0,len(s))]
    f1=open("D:\\prediction of storm and rain\\data sets\\bingbaozhenghe.txt",'w',encoding='utf-8')
    f1.write("Station_Name Station_Id_d Lat Lon Year Mon Day Hour threehouragoPRS threehouragoPRS_Sea threehouragoTEM threehouragoDPT threehouragoRHU threehouragoVAP threehouragoWIN_D_Avg_2mi threehouragoWIN_S_Avg_2mi threehouragoWIN_D_Avg_10mi threehouragoWIN_S_Avg_10mi twohouragoPRS twohouragoPRS_Sea twohouragoTEM twohouragoDPT twohouragoRHU twohouragoVAP twohouragoWIN_D_Avg_2mi twohouragoWIN_S_Avg_2mi twohouragoWIN_D_Avg_10mi twohouragoWIN_S_Avg_10mi onehouragoPRS onehouragoPRS_Sea onehouragoTEM onehouragoDPT onehouragoRHU onehouragoVAP onehouragoWIN_D_Avg_2mi onehouragoWIN_S_Avg_2mi onehouragoWIN_D_Avg_10mi onehouragoWIN_S_Avg_10mi PRE_1h"+'\n')
    for n in range(0,len(s)):
        sa[n]=str("D:\\prediction of storm and rain\\data sets\\data\\")+str(s[n])
        df=pandas.read_table(sa[n].strip(),' ')
        for i in df.index:
            if((df['Station_Id_d'][i]==54525)and(df['Year'][i]==2006)and(df['Mon'][i]==6)and(df['Day'][i]==24)and(df['Hour'][i]==9)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54528)and(df['Year'][i]==2006)and(df['Mon'][i]==6)and(df['Day'][i]==25)and(df['Hour'][i]==11)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54645)and(df['Year'][i]==2006)and(df['Mon'][i]==6)and(df['Day'][i]==25)and(df['Hour'][i]==10)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54529)and(df['Year'][i]==2006)and(df['Mon'][i]==7)and(df['Day'][i]==5)and(df['Hour'][i]==8)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54619)and(df['Year'][i]==2006)and(df['Mon'][i]==7)and(df['Day'][i]==5)and(df['Hour'][i]==9)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54623)and(df['Year'][i]==2007)and(df['Mon'][i]==5)and(df['Day'][i]==15)and(df['Hour'][i]==9)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54523)and(df['Year'][i]==2007)and(df['Mon'][i]==7)and(df['Day'][i]==10)and(df['Hour'][i]==16)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54623)and(df['Year'][i]==2008)and(df['Mon'][i]==6)and(df['Day'][i]==25)and(df['Hour'][i]==7)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54530)and(df['Year'][i]==2008)and(df['Mon'][i]==8)and(df['Day'][i]==26)and(df['Hour'][i]==17)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54428)and(df['Year'][i]==2008)and(df['Mon'][i]==8)and(df['Day'][i]==26)and(df['Hour'][i]==17)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54619)and(df['Year'][i]==2008)and(df['Mon'][i]==8)and(df['Day'][i]==28)and(df['Hour'][i]==7)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54526)and(df['Year'][i]==2009)and(df['Mon'][i]==4)and(df['Day'][i]==13)and(df['Hour'][i]==8)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54523)and(df['Year'][i]==2009)and(df['Mon'][i]==6)and(df['Day'][i]==26)and(df['Hour'][i]==10)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54528)and(df['Year'][i]==2011)and(df['Mon'][i]==7)and(df['Day'][i]==14)and(df['Hour'][i]==7)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54428)and(df['Year'][i]==2014)and(df['Mon'][i]==4)and(df['Day'][i]==23)and(df['Hour'][i]==13)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==545619)and(df['Year'][i]==2014)and(df['Mon'][i]==6)and(df['Day'][i]==1)and(df['Hour'][i]==8)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54428)and(df['Year'][i]==2014)and(df['Mon'][i]==6)and(df['Day'][i]==6)and(df['Hour'][i]==5)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54529)and(df['Year'][i]==2014)and(df['Mon'][i]==6)and(df['Day'][i]==10)and(df['Hour'][i]==6)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54530)and(df['Year'][i]==2014)and(df['Mon'][i]==6)and(df['Day'][i]==22)and(df['Hour'][i]==8)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54623)and(df['Year'][i]==2014)and(df['Mon'][i]==6)and(df['Day'][i]==22)and(df['Hour'][i]==8)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54523)and(df['Year'][i]==2014)and(df['Mon'][i]==6)and(df['Day'][i]==26)and(df['Hour'][i]==8)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54523)and(df['Year'][i]==2014)and(df['Mon'][i]==6)and(df['Day'][i]==26)and(df['Hour'][i]==8)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54623)and(df['Year'][i]==2015)and(df['Mon'][i]==4)and(df['Day'][i]==11)and(df['Hour'][i]==16)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54528)and(df['Year'][i]==2015)and(df['Mon'][i]==5)and(df['Day'][i]==17)and(df['Hour'][i]==13)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54526)and(df['Year'][i]==2015)and(df['Mon'][i]==6)and(df['Day'][i]==1)and(df['Hour'][i]==9)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54622)and(df['Year'][i]==2015)and(df['Mon'][i]==6)and(df['Day'][i]==1)and(df['Hour'][i]==10)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54527)and(df['Year'][i]==2015)and(df['Mon'][i]==6)and(df['Day'][i]==1)and(df['Hour'][i]==10)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54530)and(df['Year'][i]==2015)and(df['Mon'][i]==6)and(df['Day'][i]==1)and(df['Hour'][i]==10)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54529)and(df['Year'][i]==2015)and(df['Mon'][i]==6)and(df['Day'][i]==1)and(df['Hour'][i]==10)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54526)and(df['Year'][i]==2015)and(df['Mon'][i]==6)and(df['Day'][i]==1)and(df['Hour'][i]==10)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54530)and(df['Year'][i]==2015)and(df['Mon'][i]==6)and(df['Day'][i]==1)and(df['Hour'][i]==11)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54517)and(df['Year'][i]==2015)and(df['Mon'][i]==6)and(df['Day'][i]==22)and(df['Hour'][i]==4)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54527)and(df['Year'][i]==2015)and(df['Mon'][i]==6)and(df['Day'][i]==22)and(df['Hour'][i]==4)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54523)and(df['Year'][i]==2015)and(df['Mon'][i]==7)and(df['Day'][i]==21)and(df['Hour'][i]==10)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54528)and(df['Year'][i]==2015)and(df['Mon'][i]==7)and(df['Day'][i]==24)and(df['Hour'][i]==4)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54523)and(df['Year'][i]==2015)and(df['Mon'][i]==7)and(df['Day'][i]==24)and(df['Hour'][i]==5)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54528)and(df['Year'][i]==2015)and(df['Mon'][i]==7)and(df['Day'][i]==27)and(df['Hour'][i]==11)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54528)and(df['Year'][i]==2015)and(df['Mon'][i]==7)and(df['Day'][i]==30)and(df['Hour'][i]==8)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54619)and(df['Year'][i]==2015)and(df['Mon'][i]==8)and(df['Day'][i]==23)and(df['Hour'][i]==7)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54623)and(df['Year'][i]==2015)and(df['Mon'][i]==8)and(df['Day'][i]==28)and(df['Hour'][i]==5)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54622)and(df['Year'][i]==2015)and(df['Mon'][i]==8)and(df['Day'][i]==28)and(df['Hour'][i]==6)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54623)and(df['Year'][i]==2015)and(df['Mon'][i]==8)and(df['Day'][i]==28)and(df['Hour'][i]==8)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54526)and(df['Year'][i]==2015)and(df['Mon'][i]==9)and(df['Day'][i]==24)and(df['Hour'][i]==5)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54623)and(df['Year'][i]==2015)and(df['Mon'][i]==8)and(df['Day'][i]==29)and(df['Hour'][i]==7)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54623)and(df['Year'][i]==2015)and(df['Mon'][i]==8)and(df['Day'][i]==18)and(df['Hour'][i]==3)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54623)and(df['Year'][i]==2015)and(df['Mon'][i]==8)and(df['Day'][i]==11)and(df['Hour'][i]==7)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54623)and(df['Year'][i]==2015)and(df['Mon'][i]==7)and(df['Day'][i]==24)and(df['Hour'][i]==7)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54623)and(df['Year'][i]==2015)and(df['Mon'][i]==7)and(df['Day'][i]==27)and(df['Hour'][i]==9)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54623)and(df['Year'][i]==2015)and(df['Mon'][i]==7)and(df['Day'][i]==28)and(df['Hour'][i]==17)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54623)and(df['Year'][i]==2015)and(df['Mon'][i]==4)and(df['Day'][i]==27)and(df['Hour'][i]==8)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54623)and(df['Year'][i]==2015)and(df['Mon'][i]==5)and(df['Day'][i]==17)and(df['Hour'][i]==8)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54623)and(df['Year'][i]==2015)and(df['Mon'][i]==5)and(df['Day'][i]==17)and(df['Hour'][i]==9)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54623)and(df['Year'][i]==2015)and(df['Mon'][i]==5)and(df['Day'][i]==17)and(df['Hour'][i]==10)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54623)and(df['Year'][i]==2015)and(df['Mon'][i]==6)and(df['Day'][i]==1)and(df['Hour'][i]==8)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54623)and(df['Year'][i]==2015)and(df['Mon'][i]==6)and(df['Day'][i]==10)and(df['Hour'][i]==8)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54623)and(df['Year'][i]==2015)and(df['Mon'][i]==6)and(df['Day'][i]==10)and(df['Hour'][i]==10)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54623)and(df['Year'][i]==2015)and(df['Mon'][i]==6)and(df['Day'][i]==10)and(df['Hour'][i]==11)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54623)and(df['Year'][i]==2015)and(df['Mon'][i]==6)and(df['Day'][i]==22)and(df['Hour'][i]==7)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54529)and(df['Year'][i]==2016)and(df['Mon'][i]==6)and(df['Day'][i]==10)and(df['Hour'][i]==9)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54428)and(df['Year'][i]==2016)and(df['Mon'][i]==6)and(df['Day'][i]==15)and(df['Hour'][i]==8)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54428)and(df['Year'][i]==2016)and(df['Mon'][i]==6)and(df['Day'][i]==15)and(df['Hour'][i]==9)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54619)and(df['Year'][i]==2016)and(df['Mon'][i]==6)and(df['Day'][i]==22)and(df['Hour'][i]==11)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54619)and(df['Year'][i]==2016)and(df['Mon'][i]==6)and(df['Day'][i]==28)and(df['Hour'][i]==6)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
            if((df['Station_Id_d'][i]==54619)and(df['Year'][i]==2016)and(df['Mon'][i]==6)and(df['Day'][i]==29)and(df['Hour'][i]==22)):
                f1.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['PRS'][i-3])+' '+str(df['PRS_Sea'][i-3])+' '+str(df['TEM'][i-3])+' '+str(df['DPT'][i-3])+' '+str(df['RHU'][i-3])+' '+str(df['VAP'][i-3])+' '+str(df['WIN_D_Avg_2mi'][i-3])+' '+str(df['WIN_S_Avg_2mi'][i-3])+' '+str(df['WIN_D_Avg_10mi'][i-3])+' '+str(df['WIN_S_Avg_10mi'][i-3])+' '+str(df['PRS'][i-2])+' '+str(df['PRS_Sea'][i-2])+' '+str(df['TEM'][i-2])+' '+str(df['DPT'][i-2])+' '+str(df['RHU'][i-2])+' '+str(df['VAP'][i-2])+' '+str(df['WIN_D_Avg_2mi'][i-2])+' '+str(df['WIN_S_Avg_2mi'][i-2])+' '+str(df['WIN_D_Avg_10mi'][i-2])+' '+str(df['WIN_S_Avg_10mi'][i-2])+' '+str(df['PRS'][i-1])+' '+str(df['PRS_Sea'][i-1])+' '+str(df['TEM'][i-1])+' '+str(df['DPT'][i-1])+' '+str(df['RHU'][i-1])+' '+str(df['VAP'][i-1])+' '+str(df['WIN_D_Avg_2mi'][i-1])+' '+str(df['WIN_S_Avg_2mi'][i-1])+' '+str(df['WIN_D_Avg_10mi'][i-1])+' '+str(df['WIN_S_Avg_10mi'][i-1])+' '+str(df['PRE_1h'][i])+'\n')
    f1.close() 
    df=pandas.read_table("D:\\prediction of storm and rain\\data sets\\bingbaozhenghe.txt",' ') 
    f2=open("D:\\prediction of storm and rain\\data sets\\beijingshishibingbaoshujuji.txt",'w',encoding="utf-8")
    f2.write("Station_Name Station_Id_d Lat Lon Year Mon Day Hour threehouragoPRS threehouragoPRS_Sea threehouragoTEM threehouragoDPT threehouragoRHU threehouragoVAP threehouragoWIN_D_Avg_2mi threehouragoWIN_S_Avg_2mi threehouragoWIN_D_Avg_10mi threehouragoWIN_S_Avg_10mi twohouragoPRS twohouragoPRS_Sea twohouragoTEM twohouragoDPT twohouragoRHU twohouragoVAP twohouragoWIN_D_Avg_2mi twohouragoWIN_S_Avg_2mi twohouragoWIN_D_Avg_10mi twohouragoWIN_S_Avg_10mi onehouragoPRS onehouragoPRS_Sea onehouragoTEM onehouragoDPT onehouragoRHU onehouragoVAP onehouragoWIN_D_Avg_2mi onehouragoWIN_S_Avg_2mi onehouragoWIN_D_Avg_10mi onehouragoWIN_S_Avg_10mi PRE_1h"+'\n')
    for i in df.index:
        df['Hour'][i]+=8
    for i in df.index:
        if(df['Hour'][i]>=24):
            df['Hour'][i]-=24
            df['Day'][i]+=1
    for i in df.index:
        if((df['Mon'][i]==5)and(df['Day'][i]==32)):
            df['Mon'][i]=6
            df['Day'][i]=1 
        if((df['Mon'][i]==6)and(df['Day'][i]==31)):
            df['Mon'][i]=7
            df['Day'][i]=1
        if((df['Mon'][i]==7)and(df['Day'][i]==32)):
            df['Mon'][i]=8
            df['Day'][i]=1
        if((df['Mon'][i]==8)and(df['Day'][i]==32)):
            df['Mon'][i]=9
            df['Day'][i]=1
        if((df['Mon'][i]==9)and(df['Day'][i]==31)):
            df['Mon'][i]=10
            df['Day'][i]=1        #将世界时改为北京时
    #print("Station_Name Station_Id_d Lat Lon Year Mon Day Hour threehouragoPRS threehouragoPRS_Sea  threehouragoTEM threehouragoDPT threehouragoRHU threehouragoVAP threehouragoWIN_D_Avg_2mi threehouragoWIN_S_Avg_2mi threehouragoWIN_D_Avg_10mi threehouragoWIN_S_Avg_10mi twohouragoPRS twohouragoPRS_Sea twohouragoTEM twohouragoDPT twohouragoRHU twohouragoVAP  twohouragoWIN_D_Avg_2mi twohouragoWIN_S_Avg_2mi twohouragoWIN_D_Avg_10mi twohouragoWIN_S_Avg_10mi onehouragoPRS onehouragoPRS_Sea onehouragoTEM onehouragoDPT onehouragoRHU onehouragoVAP onehouragoWIN_D_Avg_2mi onehouragoWIN_S_Avg_2mi onehouragoWIN_D_Avg_10mi onehouragoWIN_S_Avg_10mi PRE_1h")
    for i in df.index:
        #print(dfa['Station_Name'][i],dfa['Station_Id_d'][i],dfa['Lat'][i],dfa['Lon'][i],dfa['Year'][i],dfa['Mon'][i],dfa['Day'][i],dfa['Hour'][i],dfa['threehouragoPRS'][i],dfa['threehouragoPRS_Sea'][i],dfa['threehouragoTEM'][i],dfa['threehouragoDPT'][i],dfa['threehouragoRHU'][i],dfa['threehouragoVAP'][i],dfa['threehouragoWIN_D_Avg_2mi'][i], dfa['threehouragoWIN_S_Avg_2mi'][i],dfa['threehouragoWIN_D_Avg_10mi'][i],dfa['threehouragoWIN_S_Avg_10mi'][i],dfa['twohouragoPRS'][i],dfa['twohouragoPRS_Sea'][i],dfa['twohouragoTEM'][i],dfa['twohouragoDPT'][i],dfa['twohouragoRHU'][i],dfa['twohouragoVAP'][i],dfa['twohouragoWIN_D_Avg_2mi'][i], dfa['twohouragoWIN_S_Avg_2mi'][i],dfa['twohouragoWIN_D_Avg_10mi'][i],dfa['twohouragoWIN_S_Avg_10mi'][i],dfa['onehouragoPRS'][i],dfa['onehouragoPRS_Sea'][i],dfa['onehouragoTEM'][i],dfa['onehouragoDPT'][i],dfa['onehouragoRHU'][i],dfa['onehouragoVAP'][i],dfa['onehouragoWIN_D_Avg_2mi'][i], dfa['onehouragoWIN_S_Avg_2mi'][i],dfa['onehouragoWIN_D_Avg_10mi'][i],dfa['onehouragoWIN_S_Avg_10mi'][i],dfa['PRE_1h'][i])
        f2.write(str(df['Station_Name'][i])+' '+str(df['Station_Id_d'][i])+' '+str(df['Lat'][i])+' '+str(df['Lon'][i])+' '+str(df['Year'][i])+' '+str(df['Mon'][i])+' '+str(df['Day'][i])+' '+str(df['Hour'][i])+' '+str(df['threehouragoPRS'][i])+' '+str(df['threehouragoPRS_Sea'][i])+' '+str(df['threehouragoTEM'][i])+' '+str(df['threehouragoDPT'][i])+' '+str(df['threehouragoRHU'][i])+' '+str(df['threehouragoVAP'][i])+' '+str(df['threehouragoWIN_D_Avg_2mi'][i])+' '+str(df['threehouragoWIN_S_Avg_2mi'][i])+' '+str(df['threehouragoWIN_D_Avg_10mi'][i])+' '+str(df['threehouragoWIN_S_Avg_10mi'][i])+' '+str(df['twohouragoPRS'][i])+' '+str(df['twohouragoPRS_Sea'][i])+' '+str(df['twohouragoTEM'][i])+' '+str(df['twohouragoDPT'][i])+' '+str(df['twohouragoRHU'][i])+' '+str(df['twohouragoVAP'][i])+' '+str(df['twohouragoWIN_D_Avg_2mi'][i])+' '+str(df['twohouragoWIN_S_Avg_2mi'][i])+' '+str(df['twohouragoWIN_D_Avg_10mi'][i])+' '+str(df['twohouragoWIN_S_Avg_10mi'][i])+' '+str(df['onehouragoPRS'][i])+' '+str(df['onehouragoPRS_Sea'][i])+' '+str(df['onehouragoTEM'][i])+' '+str(df['onehouragoDPT'][i])+' '+str(df['onehouragoRHU'][i])+' '+str(df['onehouragoVAP'][i])+' '+str(df['onehouragoWIN_D_Avg_2mi'][i])+' '+str(df['onehouragoWIN_S_Avg_2mi'][i])+' '+str(df['onehouragoWIN_D_Avg_10mi'][i])+' '+str(df['onehouragoWIN_S_Avg_10mi'][i])+' '+str(df['PRE_1h'][i])+'\n')
    f2.close()  #将北京时数据存入"D:\\beijingshishishujuji.txt"